import type { Metadata } from "next";
import { Raleway } from 'next/font/google';
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";
import { ReduxProvider } from '@/components/providers/redux-provider';
import AuthWrapper from "@/components/providers/creds-provider";

const raleway = Raleway({
  subsets: ['latin'],
  variable: '--font-raleway',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.className} antialiased`}> 
        <ReduxProvider>
          <AuthWrapper>
            {children}
            <Toaster />
          </AuthWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
