version: "3.9"
services:
  blockchain:
    build: ./blockchain
    ports:
      - "8545:8545"

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - blockchain

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
