version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "5000:5000"
    restart: always

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "5001:5000"
    restart: always

  extension-service:
    build:
      context: ./extension-service
    ports:
      - "5002:5000"
    restart: always

  organization-api-service:
    build:
      context: ./organization-api-service
    ports:
      - "5003:5000"
    restart: always

  verification-service:
    build:
      context: ./verification-service
    ports:
      - "5004:5000"
    restart: always
